# Generated by Django 6.0 on 2026-05-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
